server:
  port: 8084
spring:
  application:
    name: ms-goods-web
  thymeleaf:
    cache: false
  main:
  #两个实例使用feign调用同一个模块时开启
    allow-bean-definition-overriding: true
  rabbitmq:
    virtual-host: /mall
    host: 192.168.56.130
    username: mall
    password: mall
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10秒不发送就会被移除
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}@${eureka.instance.ip-address}@${server.port}

#健康检查
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always