server:
  port: 10086
spring:
  application:
    name: ms-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false
    # 拉取服务信息
    fetch-registry: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1