server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://127.0.0.1/ms_mall?serverTimezone=GMT%2B8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  rabbitmq:
    virtual-host: /mall
    username: mall
    password: mall
    host: 192.168.56.130
    template:
      exchange: mall.item.exchange
    publisher-confirms: true
#  devtools:
#    restart:
#      enabled: false #开启热部署
#  freemarker:
#    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    # 固定一下本地ip
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}@${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#健康检查
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.web: DEBUG

