server:
  port: 8083
spring:
  application:
    name: search-service
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      host: 192.168.56.130
      port: 9200
      scheme: http
  rabbitmq:
    host: 192.168.56.130
    username: mall
    password: mall
    virtual-host: /mall
  jackson:
    default-property-inclusion: non_null #jackson配置json处理时忽略null的字段
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}@${server.port}