server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.56.130
    port: 5672
    username: mall
    password: mall
    virtual-host: /mall
  redis:
    host: 192.168.56.130
    port: 6379
mall:
  sms:
    accessKeyId: 222222 #accessid
    accessKeySecret: ssss #password
    signName: dilemma商城 # 签名名称
    verifyCodeTemplate: SMS_187261422 # 模板名称