server:
  port: 8087
spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 #5秒一次心跳
    lease-expiration-duration-in-seconds: 10 #10秒不发送就移除
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}@${server.port}


