server:
  port: 10087
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
        # 基于服务定位
          enabled: true
        # 启动服务实例id名称小写支持
          lower-case-service-id: true
mall:
  jwt:
    pubKeyPath: D:/tmp/rsa/rsa.pub
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
  #优先使用ip注册
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}@${server.port}
    ip-address: 127.0.0.1
  #所属服务分组
    #app-group-name: common-server

#健康检查
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#熔断器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断时长：5000ms
#负载均衡配置
ribbon:
  connectTimeout: 1000 #链接超过时长
  ReadTimeout: 3500 #读取超过时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0  # 切换服务器重试次数

